nTest = 10000; %size of test set
TestSetChallenges= randi([0 1], nTest, chalSize);
TestSetResponses = ComputeResponseMXPUF( ...
                       x_XPw,y_XPw,x,y,feedback_a, ...
                       TestSetChallenges,nTest,chalSize ...
                       ); 

TestY = ComputeResponseMXPUF2( ...
                       Wup,wModellist,x,y,feedback_a, ...
                       TestSetChallenges,nTest,chalSize ...
                       ); 
                   
[ac, precision, recall, fscore] = accuracy(TestSetResponses,TestY);